# Generated by Django 5.0.3 on 2024-03-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdwallet',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
